# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm i
      - run: npm run build --if-present

  push_files:
    name: Copy dist files
    runs-on: ubuntu-latest
    needs: [ push_images ]
    steps:
      - uses: actions/checkout@v3
      - name: Copy .html via SSH
        uses: appleboy/scp-action@master
        with:
          host: overridetech.ru
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "dist"
          target: "/home/github/website/dist"
          overwrite: true