# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm i
      - run: npm run build --if-present

      - uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: dist/

      - uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          path: dist


      - name: Connect with SSH and rm -rf all inside dist folder
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: overridetech.ru
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf /home/github/website/dist/*

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: overridetech.ru
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "dist/"
          target: "/home/github/website/dist/"
          strip_components: 1
          overwrite: true